name: CI

on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/reuse.yml

      - name: Node version
        run: node --version
